---
- name: Change mongo config file
  ansible.builtin.template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    mode: "0644"
    force: true
  notify: "Restart database"
- name: Show info about the env this host belongs to
  ansible.builtin.debug:
    msg: "This host is in {{ env }} environment!!!"
