all:
  hosts:
    reddit-app:
  children:
    app:
      hosts:
        reddit-app:
          ansible_host: 158.160.48.2
#        appserver: 
#          ansible_host: 158.160.48.2
      vars:
         ansible_port: 22
    db:
      hosts:
        reddit-db:
          ansible_host: 158.160.96.79
#        dbserver:
#          ansible_host: 158.160.96.79

